In [24]:
import pandas as pd
import numpy as np

import warnings
from pathlib import Path
import unicodedata

pd.set_option("display.max_colwidth", None)



ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'processed'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

In [2]:
# df = pd.DataFrame(columns=[
#     'Equipo',
#     'Dorsal',
#     'Nombre',
#     'Apellido',
#     'Posición',
#     'Altura',
#     'Fecha_Nacim',
#     'Pais_Nacim',
#     'Comunidad',
#     'Nacionalidad',
#     'Licencia'
# ])

In [3]:
df = pd.read_csv(
    DATA_PATH/'Jugadores.csv',
    dtype={
        "Equipo": "object",
        "Dorsal": "object",
        "Nombre": "object",
        "Apellido": "object",
        "Posición": "object",
        "Altura": "object",
        "Fecha_Nacim": "object",
        "Pais_Nacim": "object",
        "Comunidad": "object",
        "Nacionalidad": "object",
        "Licencia": "object"
    })

In [4]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
33,BAR,44,Joel,Parra,3,202,04/04/2000,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
34,BAR,47,Dani,González,2,190,28/02/2007,ESP,CYL,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
35,CAZ,0,Marco,Spissu,1,184,05/02/1995,ITA,NaN,ITA,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
36,CAZ,00,Devin,Robinson,4,203,07/03/1995,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
37,CAZ,2,Trae,Bell-Haynes,1,188,05/09/1995,CAN,NaN,JAM,COT,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
38,CAZ,3,Justin,Wright-Foreman,1,183,27/10/1997,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
39,CAZ,4,Santi,Yusta,3,200,28/04/1997,ESP,MAD,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
40,CAZ,7,Miguel,González,2,203,20/03/1999,ESP,CYL,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...
41,CAZ,9,Matija,Lukic,2,202,19/10/2009,NLD,NaN,NLD,EUR,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,NaN
42,CAZ,10,Jaime,Fernández,4,206,15/07/2000,ESP,ARA,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...,https://github.com/DJordanV/ACB_25-26/blob/dev...

In [5]:
jugadores = []

equipo = input('Equipo: ').upper()

while True:

    dorsal = input('Dorsal: ')
    nombre = input('Nombre (sin apellido): ').title()
    apellido = input('Apellido: ').title()
    posicion = input('Posición: ')
    altura = input('Altura en cm: ')

    dia_nacim = input('Día de nacimiento (DD): ')
    mes_nacim = input('Mes de nacimiento (MM): ')
    año_nacim = input('Año de nacimiento (AAAA): ')
    fecha_nacim = dia_nacim + '/' + mes_nacim + '/' + año_nacim
    
    pais_nacim = input('País de Nacimiento: ').upper()

    if pais_nacim in ['ESP', 'ESPAÑA']:
        comunidad = input('Comunidad Autónoma: ').upper()
    else:
        comunidad = ''

    nacionalidad = input('Nacionalidad: ').upper()
    licencia = input('Licencia: ').upper()

    nueva_fila = {
        'Equipo': equipo,
        'Dorsal': dorsal,
        'Nombre': nombre,
        'Apellido': apellido,
        'Posición': posicion,
        'Altura': altura,
        'Fecha_Nacim': fecha_nacim,
        'Pais_Nacim': pais_nacim,
        'Comunidad': comunidad,
        'Nacionalidad': nacionalidad,
        'Licencia': licencia
    }

    jugadores.append(nueva_fila)

    continuar = input('Añadir otro jugador? (S/N): ').upper()
    if continuar != 'S':
        break

df = pd.concat(
    [df, pd.DataFrame(jugadores)],
    ignore_index=True
)

In [13]:
iso_paises = {
    'ESPAÑA': 'ESP',
    'ARGENTINA': 'ARG',
    'ITALIA': 'ITA',
    'CHEQUIA': 'CZE',
    'SENEGAL': 'SEN',
    'FRANCIA': 'FRA',
    'GEORGIA': 'GEO',
    'MALI': 'MLI',
    'ESTONIA': 'EST',
    'PAISES BAJOS': 'NLD',
    'SERBIA': 'SRB',
    'CROACIA': 'HRV',
    'HUNGRIA': 'HUN',
    'MONTENEGRO': 'MNE',
    'REINO UNIDO': 'GBR',
    'LITUANIA': 'LTU',
    'SUECIA': 'SWE',
    'CANADA': 'CAN',
    'JAMAICA': 'JAM',
    'URUGUAY': 'URY',
    'RUSIA': 'RUS',
    'CHAD': 'TCD',
    'TURQUIA': 'TUR',
    'REPUBLICA CENTROAFRICANA': 'CAF',
    'REPUBLICA DOMINICANA': 'DOM',
}
df.replace(iso_paises, inplace=True)

In [21]:
df['Apellido_modif'] = (
    df["Apellido"]
    .str.lower()
    .apply(lambda x: unicodedata.normalize("NFD", x).encode("ascii", "ignore").decode("utf-8"))
)

df['Foto'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/' + df['Equipo'] + '/cuerpo/' + df['Dorsal'] + '-' + df['Apellido_modif'] + '.webp?raw=true'
df['Bandera_Pais'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/' + df['Pais_Nacim'] + '.png?raw=true'
df['Bandera_Comunidad'] = np.where(df['Comunidad'] == '', '', 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/' + df['Comunidad'] + '.png?raw=true')


df = df.drop(columns='Apellido_modif')

In [22]:
columnas = ["Pais_Nacim", "Comunidad", "Nacionalidad"]

for col in columnas:
    mask = df[col].notna() & (df[col].str.len() > 3)

    if mask.any():
        warnings.warn(
            f"La columna '{col}' contiene valores con más de 3 caracteres: "
            f"{df.loc[mask, col].unique().tolist()}",
            UserWarning
        )

In [25]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
47,CAZ,18,Aleksandr,Savkov,3,208,20/06/2005,RUS,,RUS,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/18-savkov.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/RUS.png?raw=true,
48,CAZ,20,Dj,Stephens,3,198,19/12/1990,USA,,USA,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/20-stephens.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,
49,CAZ,21,Christ,Koumadje,5,224,07/07/1996,TCD,,TCD,COT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/21-koumadje.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/TCD.png?raw=true,
50,CAZ,23,Youssouf,Traoré,5,205,26/12/2006,MLI,,MLI,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/23-traore.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/MLI.png?raw=true,
51,CAZ,3,Erik,Stevenson,2,190,28/04/1999,USA,,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/3-stevenson.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,
52,CAZ,5,Lucas,Langarita,2,196,04/01/2005,ESP,ARA,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/5-langarita.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/ARA.png?raw=true
53,CAZ,5,Isaiah,Washington,1,185,20/07/1998,USA,,CAF,COT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/5-washington.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,
54,CAZ,8,Emir,Kabaca,4,208,13/12/2000,TUR,,TUR,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/8-kabaca.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/TUR.png?raw=true,
55,CAZ,11,Josh,Richardson,2,196,15/09/1993,USA,,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/11-richardson.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,
56,CAZ,12,Joel,Soriano,5,208,30/01/2000,USA,,DOM,COT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/CAZ/cuerpo/12-soriano.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,

In [10]:
# df.loc[[35,36,37,38,39,40,41,42], 'Equipo'] = 'CAZ'

In [11]:
# df = df.drop(21)

In [17]:
df.to_csv(
    PROCESSED_PATH/'Jugadores.csv',
    index=False
)